#!/bin/bash
cd /

if [[ -n "$INPUT_LOG-GROUP-NAME" && -n "$INPUT_LOG-STREAM-PREFIX" ]]; then
    python3 python_cicd.py $INPUT_APPLICATION $INPUT_ENVIRONMENT -g $INPUT_LOGGROUPNAME -s $INPUT_LOGSTREAMPREFIX
elif [[ -n "$INPUT_LOG-GROUP-NAME" && -z "$INPUT_LOG-STREAM-PREFIX" ]]; then
    python3 python_cicd.py $INPUT_APPLICATION $INPUT_ENVIRONMENT -g $INPUT_LOGGROUPNAME
elif [[ -z "$INPUT_LOG-GROUP-NAME" && -n "$INPUT_LOG-STREAM-PREFIX" ]]; then
    python3 python_cicd.py $INPUT_APPLICATION $INPUT_ENVIRONMENT -s $INPUT_LOGSTREAMPREFIX
else
    python3 python_cicd.py $INPUT_APPLICATION $INPUT_ENVIRONMENT
fi
